// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GA2GBtz9yvrPYQSLtKrNemNLKdLzshQ',
    appId: '1:224503280319:web:041d9cd3ce956b27374c0a',
    messagingSenderId: '224503280319',
    projectId: 'wydatki-9e2b3',
    authDomain: 'wydatki-9e2b3.firebaseapp.com',
    storageBucket: 'wydatki-9e2b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTHUFIGatNpGJGNn-ZaqMIUCgTwQu_IWo',
    appId: '1:224503280319:android:439b772b46aa8b7b374c0a',
    messagingSenderId: '224503280319',
    projectId: 'wydatki-9e2b3',
    storageBucket: 'wydatki-9e2b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4g3mJ7CE0g_Reu3mPR8UE5LEpEHENppY',
    appId: '1:224503280319:ios:413726af557c8e1b374c0a',
    messagingSenderId: '224503280319',
    projectId: 'wydatki-9e2b3',
    storageBucket: 'wydatki-9e2b3.appspot.com',
    iosClientId: '224503280319-oq4cpbpvfh188ab4if0hqonfj0bkgnaf.apps.googleusercontent.com',
    iosBundleId: 'com.sebastiangirsza.wydatki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4g3mJ7CE0g_Reu3mPR8UE5LEpEHENppY',
    appId: '1:224503280319:ios:413726af557c8e1b374c0a',
    messagingSenderId: '224503280319',
    projectId: 'wydatki-9e2b3',
    storageBucket: 'wydatki-9e2b3.appspot.com',
    iosClientId: '224503280319-oq4cpbpvfh188ab4if0hqonfj0bkgnaf.apps.googleusercontent.com',
    iosBundleId: 'com.sebastiangirsza.wydatki',
  );
}
